### ISSUE TITLE
Arch Linux, Font Issue

### ISSUE THREAD

**Issue by KoboDev** [PhantomGamers/SFP#132]
[SFP.log](https://github.com/PhantomGamers/SFP/files/11801161/SFP.log)

Switched to Arch so I could have a better performance experience after the Big Steam UI update, problem is, everytime i try to launch, it crashes because of an font error. Saying that `The Font Family cannot be null or empty`. I just want to inject my skin so I dont cringe every second I look at the new UI. (Or in many other peoples cases, have their computer crash due to an memory leak.)

**Comment by PhantomGamers** [comment]
[According to this](https://github.com/AvaloniaUI/Avalonia/issues/4427#issuecomment-669173654), installing [this package](https://aur.archlinux.org/packages/ttf-ms-fonts/) should fix it.

**Comment by PhantomGamers** [comment]
Also just to have the error in plain text here, it is:
```
System.InvalidOperationException: Default font family name can't be null or empty.
   at Avalonia.Media.FontManager..ctor(IFontManagerImpl platformImpl) in /_/src/Avalonia.Base/Media/FontManager.cs:line 37
   at Avalonia.Media.FontManager.get_Current() in /_/src/Avalonia.Base/Media/FontManager.cs:line 59
   at Avalonia.Media.Typeface.get_GlyphTypeface() in /_/src/Avalonia.Base/Media/Typeface.cs:line 87
   at Avalonia.Rendering.Composition.Compositor.get_DiagnosticTextRenderer() in /_/src/Avalonia.Base/Rendering/Composition/Compositor.cs:line 55
   at Avalonia.Rendering.Composition.Compositor.CreateCompositionTarget(Func`1 surfaces) in /_/src/Avalonia.Base/Rendering/Composition/Compositor.Factories.cs:line 17
   at Avalonia.Rendering.Composition.CompositingRenderer..ctor(IRenderRoot root, Compositor compositor, Func`1 surfaces) in /_/src/Avalonia.Base/Rendering/Composition/CompositingRenderer.cs:line 54
   at Avalonia.Controls.TopLevel..ctor(ITopLevelImpl impl, IAvaloniaDependencyResolver dependencyResolver) in /_/src/Avalonia.Controls/TopLevel.cs:line 188
   at Avalonia.Controls.WindowBase..ctor(IWindowBaseImpl impl, IAvaloniaDependencyResolver dependencyResolver) in /_/src/Avalonia.Controls/WindowBase.cs:line 55
   at Avalonia.Controls.Window..ctor(IWindowImpl impl) in /_/src/Avalonia.Controls/Window.cs:line 223
   at FluentAvalonia.UI.Windowing.AppWindow..ctor()
   at SFP_UI.Views.MainWindow..ctor() in /home/runner/work/SFP/SFP/SFP_UI/Views/MainWindow.axaml.cs:line 23
   at SFP_UI.App.StartMainWindow() in /home/runner/work/SFP/SFP/SFP_UI/App.axaml.cs:line 107
   at SFP_UI.App.OnFrameworkInitializationCompleted() in /home/runner/work/SFP/SFP/SFP_UI/App.axaml.cs:line 39
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Avalonia.Threading.SendOrPostCallbackDispatcherOperation.InvokeCore() in /_/src/Avalonia.Base/Threading/DispatcherOperation.cs:line 392
   at Avalonia.Threading.DispatcherOperation.Execute() in /_/src/Avalonia.Base/Threading/DispatcherOperation.cs:line 262
   at Avalonia.Threading.Dispatcher.ExecuteJob(DispatcherOperation job) in /_/src/Avalonia.Base/Threading/Dispatcher.Queue.cs:line 122
   at Avalonia.Threading.Dispatcher.ExecuteJobsCore() in /_/src/Avalonia.Base/Threading/Dispatcher.Queue.cs:line 153
   at Avalonia.Threading.Dispatcher.Signaled() in /_/src/Avalonia.Base/Threading/Dispatcher.Queue.cs:line 133
   at Avalonia.X11.X11PlatformThreading.CheckSignaled() in /_/src/Avalonia.X11/X11PlatformThreading.cs:line 119
   at Avalonia.X11.X11PlatformThreading.RunLoop(CancellationToken cancellationToken) in /_/src/Avalonia.X11/X11PlatformThreading.cs:line 192
   at Avalonia.Threading.DispatcherFrame.Run(IControlledDispatcherImpl impl) in /_/src/Avalonia.Base/Threading/DispatcherFrame.cs:line 117
   at Avalonia.Threading.Dispatcher.PushFrame(DispatcherFrame frame) in /_/src/Avalonia.Base/Threading/Dispatcher.MainLoop.cs:line 53
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken) in /_/src/Avalonia.Base/Threading/Dispatcher.MainLoop.cs:line 80
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 127
   at SFP_UI.Program.Main(String[] args) in /home/runner/work/SFP/SFP/SFP_UI/Program.cs:line 41
```

**Comment by KoboDev** [comment]
> [According to this](https://github.com/AvaloniaUI/Avalonia/issues/4427#issuecomment-669173654), installing [this package](https://aur.archlinux.org/packages/ttf-ms-fonts/) should fix it.

I built the package and self-installed, rebooted and all. Still not working.
[SFP.6.log](https://github.com/PhantomGamers/SFP/files/11818056/SFP.6.log)

Is there something else I should've done?

**Comment by PhantomGamers** [comment]
What is your system language set to?

**Comment by PhantomGamers** [comment]
Also have you tried running `fc-cache --force`, as was also suggested in the thread I initially linked to.

**Comment by PhantomGamers** [comment]
For additional record keeping purposes: This is actually an upstream issue with SkiaSharp, not with Avalonia specifically.

https://github.com/mono/SkiaSharp/issues/1181

**Comment by KoboDev** [comment]
> What is your system language set to?

Default font: Sans regular
Desktop font: system-ui regular
document font: cantarell Regular
Monospace font: source code pro regular
window title font: sans bold



> Also have you tried running `fc-cache --force`, as was also suggested in the thread I initially linked to.

also tried this, did not work.

**Comment by PhantomGamers** [comment]
Does SFP 48 have the same problem? And I see the fonts you use, but does that mean your system language is set to English?

**Comment by KoboDev** [comment]
> Does SFP 48 have the same problem? And I see the fonts you use, but does that mean your system language is set to English?

Ill try 48, and yes my system language is set to English.

**Comment by KoboDev** [comment]
Update: tried 48, still not working.
[SFP.log](https://github.com/PhantomGamers/SFP/files/11848615/SFP.log)

**Comment by PhantomGamers** [comment]
I changed how my attempted fix works and it's available in this nightly build if you want to test

https://nightly.link/PhantomGamers/SFP/actions/runs/5360521115/SFP_UI-linux-x64-SelfContained-9e6cedbc94d2b9469d3ea3f224253854b449ab10.zip

If this doesn't work I'm not really sure what else to try, I guess maybe I'd have to embed a font for Linux, though there are quite a few Linux users that are successfully using the current version of SFP without this error... hm

**Comment by PhantomGamers** [comment]
This might be fixed in https://github.com/PhantomGamers/SFP/releases/tag/0.0.49 but I need confirmation

**Comment by KoboDev** [comment]
I tested 0.0.52 and It fixes it.
Sorry for not giving more responses I was busy doing unrelated irl stuff.
